#!/usr/bin/env perl
use strict;
use warnings;

use Mojolicious::Lite;
use Mojo::JSON qw(decode_json encode_json);
use Mojolicious::Plugin::Authentication;
use Acme::MetaSyntactic qw( norse_mythology );

my $clients = {};

my $meta = Acme::MetaSyntactic->new( category => ':all' );
my $chickens = {
    alice => {
        x   => 4,
        y   => 3,
        age => 1,
    },
};

my $eggs = {};

my $coop = {
    width       => 640,
    height      => 480,
    num_x_cells => 16,
    num_y_cells => 12,
};

my $seconds_per_tick = 3;

Mojo::IOLoop->recurring( $seconds_per_tick => sub {
    npc_turn();
});

get '/' => sub {
    my $controller = shift;
    $controller->stash( coop => $coop );
    $controller->render( template => 'index' );
};

get '/game.js' => sub {
    my $controller = shift;
    $controller->stash( coop => $coop );
    $controller->render( template => 'game', format => 'js' );
};

websocket '/game' => sub {
    my $controller = shift;

    app->log->debug( sprintf 'Client connected: %s', $controller->tx );
    my $id = sprintf "%s", $controller->tx->connection;
    $clients->{$id} = $controller->tx;
    app->log->debug( 'id: ' . $id );

    # Opened
    $controller->app->log->debug('WebSocket opened');

    # Allow inactivity indefinitely
    $controller->inactivity_timeout(0);

    # Incoming message
    $controller->on(
        message => sub {
            my ( $c, $message ) = @_;
            app->log->debug("incoming: $message");
            if ( my $j = decode_json $message ) {
                app->log->debug( $j->{cmd} );
                do_msg( c => $c, j => $j );
            }
            update_clients();
        }
    );

    # Closed
    $controller->on(
        finish => sub {
            my ( $c, $code, $reason ) = @_;
            $c->app->log->debug("WebSocket closed with status $code");
            delete $clients->{$id};
            update_clients();
        }
    );
};

sub do_msg {
    my (%args) = @_;

    my $c        = $args{c};
    my $json_msg = $args{j};
    my $id = $c->tx->connection;

    given ( $json_msg->{cmd}) {
      when ('AUTHENTICATE') {
        $c->authenticate( $json_msg->{name}, $json_msg->{code} );
      }
      when ('DE_AUTHENTICATE'){
        $c->logout();
        $c->session( expires => 1 );
      }
      when ('MOVE'){
        if ( $c->is_user_authenticated ) {
        }
        else {
        }
      }
      when ('DESTINATION'){
        # set entity's destination
      }
    }

    return;
}

sub update_clients {
    my (%args) = @_;

    for ( keys %$clients ) {
        $clients->{$_}->send(
            {
                json => {
                    chickens => $chickens,
                    eggs => $eggs,
                }
            }
        );
    }

    return;
}

sub npc_turn {
    app->log->debug('TICK');

    for my $chicken ( keys %$chickens ) {
        log_chicken( chicken => $chicken );
        move_chicken( chicken => $chicken );
        lay_egg( chicken => $chicken );
        age_chicken( chicken => $chicken );
    }

    for my $egg ( keys %$eggs )
    {
      log_egg( egg => $egg );
      age_egg( egg => $egg );
    }

    update_clients( clients => $clients );
    return;
}

sub log_chicken {
  my (%args) = @_;
  app->log->debug( "\t"
    . 'x:'. $chickens->{ $args{chicken} }->{x} . "\t"
    . 'y:'. $chickens->{ $args{chicken} }->{y} . "\t"
    . "age: \t". $chickens->{ $args{chicken} }->{age} . "\t"
    . $args{chicken} . "\t"
  );
  return;
}

sub log_egg {
  my (%args) = @_;
  app->log->debug( "\t"
    . 'x:'. $eggs->{ $args{egg} }->{x} . "\t"
    . 'y:'. $eggs->{ $args{egg} }->{y} . "\t"
    . "age: \t" . $eggs->{ $args{egg} }->{age} . "\t"
    . $args{egg} . "\t"
  );
  return;
}

sub move_chicken {
    my (%args) = @_;

    my @moves = ( 'up', 'down', 'left', 'right' );
    my $move_direction   = $moves[rand @moves];
    move_entity(
      entity => \$chickens->{ $args{chicken} },
      direction => $move_direction,
      distance => 1,
    );
    return;
}

sub move_entity {
  my (%args) = @_;

  ${$args{entity}}->{y} -= ( $args{direction} eq 'up') ? $args{distance} : 0;
  ${$args{entity}}->{y} += ( $args{direction} eq 'down') ? $args{distance} : 0;
  ${$args{entity}}->{x} -= ( $args{direction} eq 'left') ? $args{distance} : 0;
  ${$args{entity}}->{x} += ( $args{direction} eq 'right') ? $args{distance} : 0;

  ${$args{entity}}->{y} %= $coop->{num_y_cells};
  ${$args{entity}}->{x} %= $coop->{num_x_cells};

  # calculate new position
  # if new position legal, set pos = new postion
  # else, pos = old pos
  #
  # position is legal if: no other entity is in that position ( besides self )
  # for each entity in the world, is it in new_postion

  return;
}

sub age_chicken {
    my (%args) = @_;
    $chickens->{ $args{chicken} }->{age} += 1;
    if ( $chickens->{ $args{chicken} }->{age} > 111 ) {
        app->log->debug( "\t" . $args{chicken} . ' died of old age!' );
        delete( $chickens->{ $args{chicken} } );
    }
    return;
}

sub lay_egg {
    my (%args) = @_;

    if (
      $chickens->{ $args{chicken} }->{age} % 15 == 0
      && (scalar keys %$chickens)<15
      && (int rand(3)) == 2
    ) {
        my $name = $args{chicken} . '_' . $meta->name();
        $eggs->{$name}->{x}   = $chickens->{ $args{chicken} }->{x};
        $eggs->{$name}->{y}   = $chickens->{ $args{chicken} }->{y};
        $eggs->{$name}->{age} = 0;
    }
    return;
}

sub age_egg {
    my (%args) = @_;
    $eggs->{ $args{egg} }->{age} += 1;
    if ( $eggs->{ $args{egg} }->{age} > 5 )
    {
        app->log->debug( "\t" . $args{egg} . ' hatched!' );
        my $chicken = delete($eggs->{ $args{egg} });
        $chickens->{ $args{egg} } = $chicken;
    }
    return;
}

app->start;
__DATA__

@@ index.html.ep
% layout 'default';
% title 'bawk';
<canvas id='coop' width='<%= $coop->{width} %>' height='<%= $coop->{height} %>'></canvas>
<h1>bawk, bawk</h1>
<p id='connection_status'>not connected</p>
<p id='list'></p>
<script src='game.js'></script>

@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
  <head><title><%= title %></title></head>
  <body><%= content %></body>
</html>
